apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  source:
    repoURL: https://github.com/soufiiyane/wordpress-tmt.git
    targetRevision: main
    path: manifests
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true